create table Customurs
(
Customurs_ID number generated by default as identity,
customur_fname varchar2(10) not null,
customur_lname varchar2(10) not null,
customur_street varchar2(30) ,
customur_city varchar2(10) ,
customur_phone NUMBER(10) not null,
customur_email varchar2(20)UNIQUE,
referred_by VARCHAR2(10),
CONSTRAINT cust_pk PRIMARY key(Customurs_ID)

);

ALTER TABLE Customurs MODIFY (customur_city VARCHAR2(30));

INSERT INTO Customurs (customur_fname, customur_lname, customur_street, customur_city, customur_phone, customur_email, referred_by) VALUES ('Alice', 'Johnson', '123 Elm St', 'Seattle', 4255550123, 'alice.johnson@.com', NULL);
INSERT INTO Customurs (customur_fname, customur_lname, customur_street, customur_city, customur_phone, customur_email, referred_by) VALUES ('Bob', 'Smith', '456 Oak St', 'Denver', 3035550456, 'bob.smith@e.com', 'Alice');
INSERT INTO Customurs (customur_fname, customur_lname, customur_street, customur_city, customur_phone, customur_email, referred_by) VALUES ('Charlie', 'Davis', '789 Pine St', 'Austin', 5125550789, '.davis@e.com', 'Bob');
INSERT INTO Customurs (customur_fname, customur_lname, customur_street, customur_city, customur_phone, customur_email, referred_by) VALUES ('Diana', 'Clark', '135 Maple St', 'Portland', 5035550912, 'd.clark@e.com', NULL);
INSERT INTO Customurs (customur_fname, customur_lname, customur_street, customur_city, customur_phone, customur_email, referred_by) VALUES ('Ethan', 'Martinez', '246 Cedar St', 'San Francisco', 4155550345, 'etn.mtinez@ee.com', 'Charlie');
INSERT INTO Customurs (customur_fname, customur_lname, customur_street, customur_city, customur_phone, customur_email, referred_by) VALUES ('Ethan', 'Martinez', '246 Cedar St', 'SF', 4155550345, 'eth.martinez@', NULL);

select*from Customurs;


CREATE table Orders
(
--order_numb
Orders_NUMBER number generated by default as identity,
customur_numb number,
order_date date,
credit_card_numb NUMBER(5),
order_filled varchar2(10),
credit_card_exp_date date,

CONSTRAINT Orders_pk PRIMARY KEY (Orders_NUMBER),
CONSTRAINT customur_numb_fk FOREIGN KEY ( Orders_NUMBER) REFERENCES Customurs (Customurs_ID)

);



INSERT INTO Orders (customur_numb, order_date, credit_card_numb, order_filled, credit_card_exp_date) VALUES (1, SYSDATE, 12345, 'Yes', ADD_MONTHS(SYSDATE, 12));
INSERT INTO Orders (customur_numb, order_date, credit_card_numb, order_filled, credit_card_exp_date) VALUES (2, SYSDATE, 54321, 'No', ADD_MONTHS(SYSDATE, 12));
INSERT INTO Orders (customur_numb, order_date, credit_card_numb, order_filled, credit_card_exp_date) VALUES (3, SYSDATE, 67890, 'Yes', ADD_MONTHS(SYSDATE, 12));
INSERT INTO Orders (customur_numb, order_date, credit_card_numb, order_filled, credit_card_exp_date) VALUES (4, SYSDATE, 98765, 'No', ADD_MONTHS(SYSDATE, 12));
INSERT INTO Orders (customur_numb, order_date, credit_card_numb, order_filled, credit_card_exp_date) VALUES (6, SYSDATE, 13579, 'Yes', ADD_MONTHS(SYSDATE, 12));

SELECT * FROM orders;


create table order_lines
(
order_numb number,
Books_id number ,
PRIMARY KEY (order_numb,Books_id),
foreign key(order_numb)REFERENCES Orders(Orders_NUMBER),
foreign key(Books_id)REFERENCES Books(Books_id),
quantity number(3)not null,
cost_each number(4,2)not null,
cost_line number(7) not null,
shipped varchar2(15) not null

);


INSERT INTO order_lines (order_numb, Books_id, quantity, cost_each, cost_line, shipped) VALUES (1, 1, 2, 19.99, 39.98, 'Yes');
INSERT INTO order_lines (order_numb, Books_id, quantity, cost_each, cost_line, shipped) VALUES (2, 2, 1, 29.99, 29.99, 'No');
INSERT INTO order_lines (order_numb, Books_id, quantity, cost_each, cost_line, shipped) VALUES (3, 3, 3, 24.99, 74.97, 'Yes');
INSERT INTO order_lines (order_numb, Books_id, quantity, cost_each, cost_line, shipped) VALUES (4, 4, 1, 14.99, 14.99, 'No');
INSERT INTO order_lines (order_numb, Books_id, quantity, cost_each, cost_line, shipped) VALUES (5, 5, 2, 19.99, 39.98, 'Yes');

SELECT * FROM Books;
SELECT * FROM orders;






create table Books
(
Books_id number generated by default as identity, 
author_id number,
title VARCHAR2(20),
publisher_id number,
source_id number,
retail_price number(4,2),
number_on_hand  number(3),
CONSTRAINT books_pk PRIMARY key(Books_id),
CONSTRAINT publisher_id_fk FOREIGN KEY (publisher_id) REFERENCES Publishers(publishers_id),
CONSTRAINT author_id_fk FOREIGN KEY (author_id) REFERENCES  Authors(author_id),
CONSTRAINT source_id_fk FOREIGN KEY (source_id ) REFERENCES  Sources(source_id)


);

---------------------
select Books.title, Books.publisher_id, Publishers.publishers_id , Publishers.Publishers_name
from books , publishers
where Books.publisher_id = Publishers.publishers_id and publisher_id=3;
-------------------------------
-----------------------
select b.title, b.publisher_id, e.publishers_id, e.Publishers_name
    from Books b, Publishers e
  where b.publisher_id = e.publishers_id;
-------------------------

select b.Books_id, b.title, e.publishers_id, e.Publishers_name
        from Books b, Publishers e
      where b.publisher_id(+)= e.publishers_id and publishers_id=3 ;




INSERT INTO Books (author_id, title, publisher_id, source_id, retail_price, number_on_hand) VALUES (1, 'Harry Pottee', 1, 1, 19.99, 10);
INSERT INTO Books (author_id, title, publisher_id, source_id, retail_price, number_on_hand) VALUES (2, 'A Game of Thrones', 2, 2, 29.99, 8);
INSERT INTO Books (author_id, title, publisher_id, source_id, retail_price, number_on_hand) VALUES (3, 'The Shining', 3, 3, 24.99, 5);
INSERT INTO Books (author_id, title, publisher_id, source_id, retail_price, number_on_hand) VALUES (4, 'Murder ', 4, 4, 14.99, 12);
INSERT INTO Books (author_id, title, publisher_id, source_id, retail_price, number_on_hand) VALUES (5, 'The Hobbit', 5, 5, 19.99, 7);

SELECT * FROM books;




SELECT table_name 
FROM all_tables 
WHERE table_name IN ('PUBLISHERS', 'AUTHORS', 'SOURCES');



create  table Publishers
(publishers_id number generated by default as identity,
Publishers_name varchar2(20),
CONSTRAINT Publishers_pk PRIMARY key(publishers_id)

);
drop  table Author;




INSERT INTO Publishers (Publishers_name) VALUES ('Penguin Random House');  
INSERT INTO Publishers (Publishers_name) VALUES ('HarperCollins');       
INSERT INTO Publishers (Publishers_name) VALUES ('Simon & Schuster');     
INSERT INTO Publishers (Publishers_name) VALUES ('Hachette Book Group');   
INSERT INTO Publishers (Publishers_name) VALUES ('Macmillan');            

select*from Publishers;


create table Authors
(author_id number generated by default as identity,
author_name VARCHAR2(20),
CONSTRAINT author_pk PRIMARY KEY(author_id)
);


INSERT INTO Authors (author_name) VALUES ('J.K. Rowling');               -- author_id = 1
INSERT INTO Authors (author_name) VALUES ('George R.R. Martin');         -- author_id = 2
INSERT INTO Authors (author_name) VALUES ('Stephen King');               -- author_id = 3
INSERT INTO Authors (author_name) VALUES ('Agatha Christie');             -- author_id = 4
INSERT INTO Authors (author_name) VALUES ('J.R.R. Tolkien');             -- author_id = 5





create table Sources
(
source_id number generated by default as identity,
source_name varchar2(30)not null,
source_street VARCHAR2(30),
source_city VARCHAR2(30),
source_phone VARCHAR2(30)not null,
CONSTRAINT sources_pk PRIMARY KEY(source_id)
);

INSERT INTO Sources (source_name, source_street, source_city, source_phone) VALUES ('Bookstore A', '101 Fiction Ave', 'New York', '2125551234');  -- source_id = 1
INSERT INTO Sources (source_name, source_street, source_city, source_phone) VALUES ('Bookstore B', '202 Literature Blvd', 'Los Angeles', '3105555678');  -- source_id = 2
INSERT INTO Sources (source_name, source_street, source_city, source_phone) VALUES ('Bookstore C', '303 Novel St', 'Chicago', '3125559012');  -- source_id = 3
INSERT INTO Sources (source_name, source_street, source_city, source_phone) VALUES ('Bookstore D', '404 Story Ln', 'Houston', '7135553456');  -- source_id = 4
INSERT INTO Sources (source_name, source_street, source_city, source_phone) VALUES ('Bookstore E', '505 Read St', 'Miami', '3055557890');  -- source_id = 5






SELECT * FROM Books;
SELECT * FROM Customurs;
SELECT * FROM Publishers;
SELECT * FROM Authors;
SELECT * FROM sources;
SELECT * FROM orders;

select title from books where books_id=4;
select title from books where books_id=5;

select customur_city from Customurs where CUSTOMUR_FNAME='Bob' ;




select * from user_tables;

select Customurs_ID, customur_fname || ' '|| customur_lname as "full name",customur_street, customur_city, customur_phone, customur_email, referred_by 
from customurs
where customur_fname like '%__ice' or customur_lname = ' Johnson' or customur_city  like '%__attle' ;


SELECT table_name FROM user_tables ;




